"""Added room to Transaction table

Revision ID: 64cbaa4b7c90
Revises: e297974d0701
Create Date: 2026-07-22 19:52:31.600883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64cbaa4b7c90"
down_revision: Union[str, Sequence[str], None] = "e297974d0701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("room_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transactions", "rooms", ["room_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "room_id")
    # ### end Alembic commands ###
