"""Added invite_token column to Room

Revision ID: e297974d0701
Revises: ccfcd7c99475
Create Date: 2026-07-14 20:39:09.072259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e297974d0701"
down_revision: Union[str, Sequence[str], None] = "ccfcd7c99475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("invite_token", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "rooms", ["invite_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="unique")
    op.drop_column("rooms", "invite_token")
    # ### end Alembic commands ###
